[build]
    buildCommand = "chmod +x ./mvnw && ./mvnw -DoutputFile=target/mvn-dependency-list.log -B -DskipTests clean dependency:list install"
    buildCommand = "git submodule update --init --recursive"