name: 'Submodules Sync'

on: 
  push:
    branches:
      - main

  workflow_dispatch:

jobs: 
  submodule-checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive